// Generated by https://quicktype.io

export interface BibleData {
    query:        string;
    canonical:    string;
    parsed:       Array<number[]>;
    passage_meta: PassageMeta[];
    passages:     string[];
}


export interface Passages{passages:string[]}